function getCookie(name) {
  var value = "; " + document.cookie;
  var parts = value.split("; " + name + "=");
  if (parts.length == 2) return parts.pop().split(";").shift();
}

angular.module('whatsspy-translate', ['pascalprecht.translate']).
config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
    /* PLEASE NOTE that spaces etc. are all of importance here. You also must escape ' (by using \') */
    /* Use your gitlab/real name here to identify your work */
    TRANSLATOR: '',
    MENU_LOGIN: 'Login',
    MENU_OVERVIEW: 'Overview',
    MENU_COMPARE: 'Compare',
    MENU_TIMELINE: 'Timeline',
    MENU_STATS: 'Statistics',
    MENU_ABOUT: 'About / Help',
    MENU_USER: 'Public user',
    MENU_GROUP: 'Public group',
    MENU_LOADING: 'Loading new data ...',
    MENU_STATUS: 'status',
    MENU_TRACKER_ONLINE: 'Tracker online',
    MENU_TRACKER_OFFLINE: 'Tracker offline',
    MENU_TRACKER_NOAUTH: 'not authenticated',
    MENU_TRACKER_USERS: 'users',
    MENU_TRACKER_REFRESH: 'Click to refresh the data loaded into the web-app.',
    MENU_POC: 'Proof of Concept',
    FOOTER_VERSION: 'Version',
    FOOTER_V_BEHIND: 'Behind',
    LOGIN_WELCOME: 'Welcome!',
    LOGIN_WELCOME_MSG: 'Welcome to the WhatsSpy Public PoC! Before you start tracking please read the',
    LOGIN_LICENSE: 'license',
    LOGIN_LOGIN_HEAD: 'Login',
    LOGIN_AUTH_NOTIFY: 'It seems you are not yet authenticated. Please login to view and manage the tracker.',
    LOGIN_PASS_FIELD: 'Password',
    LOGIN_SIGN_IN_BTN: 'Sign in',
    LOGIN_RESET_BTN: 'Reset',
    LOGIN_PASS_PLACEHOLDER: 'password ...',
    TOKEN_INVALID: 'Invalid token:',
    OVERVIEW_TOKEN_INVALID: 'You are not allowed to view this user because the token is or became invalid.',
    OVERVIEW_TOKEN_INFO_STRONG: 'Shared user profile:',
    OVERVIEW_TOKEN_INFO: 'This is a shared user profile created by the hoster of this WhatsSpy Public instance. The timeline contains just a snapshot of the last statusess.',
    OVERVIEW_FILTERS: 'Filters',
    OVERVIEW_FILTER_PHONE: 'Search by phone number ...',
    OVERVIEW_FILTER_NAME_TITLE: 'Use name|name to filter on multiple names.',
    OVERVIEW_FILTER_NAME: 'Search by name ...',
    OVERVIEW_INFO_STATUS: 'The system is checking all statuses',
    OVERVIEW_INFO_STATUS_FROM: 'from',
    OVERVIEW_INFO_STATUS_CONTACTS: 'contacts',
    OVERVIEW_INFO_STATUS_SINCE: 'since',
    OVERVIEW_INFO_PRIV: 'Contacts that have "last seen" set to "nobody" will be',
    OVERVIEW_INFO_PRIV_LINK: 'tracked anyway',
    OVERVIEW_INFO_LIVE: 'The information on this page is not live, you can refresh this page by clicking the gray timestamp in the "status" panel.',
    OVERVIEW_INFO_TIMESPAN: 'Beside the timeline, all information is from since you started tracking this contact (unless noted otherwise).',
    OVERVIEW_INFO_VERIFY: 'contacts will be verified within 5-10 minutes,',
    OVERVIEW_INFO_RELOAD: 'reload data',
    OVERVIEW_INFO_RELOAD_2: 'to check again.',
    OVERVIEW_ADD: 'Add Contact',
    OVERVIEW_IMPORT: 'Import Google Contacts',
    OVERVIEW_MANAGE_GROUPS: 'Manage groups',
    OVERVIEW_MANAGE_PERF: 'Performance options',
    OVERVIEW_EXPAND: 'Expand view',
    OVERVIEW_COLLAPSE: 'Collapse view',
    OVERVIEW_EDIT: 'Edit',
    OVERVIEW_CONTACT_SINCE: 'tracking since',
    OVERVIEW_CONTACT_LASTSEEN: 'last seen',
    OVERVIEW_CONTACT_NOTIF: 'notifications enabled',
    OVERVIEW_CONTACT_SHARING: 'profile sharing enabled',
    OVERVIEW_NO_INFO: 'No information available ..',
    OVERVIEW_CLICK_LOAD: 'Click to load data',
    OVERVIEW_CLICK_LOAD_TIMELINE: 'Load timeline',
    OVERVIEW_CONTACT_H_ANALYTICS: 'Analytics / Information',
    OVERVIEW_CONTACT_ANALYTICS_OVERVIEW: 'Overview',
    OVERVIEW_CONTACT_ANALYTICS_OPENOVERVIEW: 'Opened overview',
    OVERVIEW_CONTACT_ANALYTICS_TIME_OVERVIEW: 'Time overview',
    OVERVIEW_CONTACT_ANALYTICS_STATUS: 'Status Messages',
    OVERVIEW_CONTACT_ANALYTICS_PICS: 'Profile pictures',
    OVERVIEW_CONTACT_OPENED_H: 'Opened WhatsApp client',
    OVERVIEW_CONTACT_TABLE_1D: '(24h) today',
    OVERVIEW_CONTACT_TABLE_7D: '(07d) last 7 days',
    OVERVIEW_CONTACT_TABLE_14D: '(14d) last two weeks',
    OVERVIEW_CONTACT_TABLE_31D: '(31d) last month',
    OVERVIEW_CONTACT_TABLE_xD: '(---) all time',
    OVERVIEW_CONTACT_TRACKING_SINCE: 'Tracking since',
    OVERVIEW_CONTACT_TIME_SPENT_WA: 'Time spent on WhatsApp',
    OVERVIEW_CONTACT_LOADING_INFO: 'Loading information ...',
    OVERVIEW_CONTACT_SWITCH_HOUR_VIEW: 'Show per hour',
    OVERVIEW_CONTACT_SWITCH_WEEKDAY_VIEW: 'Show per weekday',
    OVERVIEW_CONTACT_H_OPENING_WA_WEEKDAY: 'Opening WhatsApp per weekday',
    OVERVIEW_CONTACT_H_OPENING_WA_HOUR: 'Opening WhatsApp per hour',
    OVERVIEW_CONTACT_H_TIME_WA_WEEKDAY: 'Time on WhatsApp per weekday',
    OVERVIEW_CONTACT_H_TIME_WA_HOUR: 'Time on WhatsApp per hour',
    OVERVIEW_CONTACT_H_PRIV_STATUS: 'Privacy / Online status',
    OVERVIEW_CONTACT_PRIV_STATUS: 'Privacy',
    OVERVIEW_CONTACT_ONLINE_EVENTS: 'Online events',
    OVERVIEW_CONTACT_H_LASTSEEN: 'Last seen',
    OVERVIEW_PRIVACY_SETTINGS_PUBLIC: 'everyone',
    OVERVIEW_PRIVACY_SETTINGS_FRIENDS: 'contacts*',
    OVERVIEW_PRIVACY_LAST_CHANGE: 'changed to',
    OVERVIEW_PRIVACY_LAST_CHANGE_AT: 'at',
    OVERVIEW_PRIVACY_H_PROF_PIC: 'Profile pic',
    OVERVIEW_PRIVACY_H_STATUS: 'Status messages',
    OVERVIEW_PRIVACY_TRACK_NOTICE: 'Profile picture and status message are checked every 2 hours.',
    OVERVIEW_PRIVACY_ASSUMPTION: 'Assuming this user does not have the tracker number in his contact list. If this is the case \'contacts only\' will be interpreted as \'everyone\' in this view.',
    OVERVIEW_LOG_FROM: 'from',
    OVERVIEW_LOG_TILL: 'till',
    OVERVIEW_LOG_NOW: 'now',
    OVERVIEW_NO_ACC: 'No tracking accounts ..',
    OVERVIEW_ADD_CONTACT_H: 'Add contact by phone number',
    OVERVIEW_ADD_CONTACT_PHONE: 'Phone number',
    OVERVIEW_ADD_CONTACT_PLACEHOLDER_COUNTRYCODE: 'countrycode ...',
    OVERVIEW_ADD_CONTACT_PLACEHOLDER_PHONE: 'phone number ...',
    OVERVIEW_ADD_CONTACT_NAME: 'Contact name',
    OVERVIEW_ADD_CONTACT_GROUP: 'Groups',
    OVERVIEW_ADD_CONTACT_NOTICE: 'The new contact will be verified as an WhatsApp user and added to the tracker within 5-10 minutes. After this you can find the contact in the overview list.',
    OVERVIEW_ADD_CONTACT_ADD: 'Add contact',
    OVERVIEW_ADD_CONTACT_CLOSE: 'Close',
    OVERVIEW_EDIT_CONTACT_H: 'Edit contact name',
    OVERVIEW_EDIT_CONTACT_PHONE: 'Phone number',
    OVERVIEW_EDIT_CONTACT_NAME: 'Contact name',
    OVERVIEW_EDIT_CONTACT_NAME_PLACEHOLDER: '(optional) name of contact',
    OVERVIEW_EDIT_CONTACT_GROUPS: 'Groups',
    OVERVIEW_EDIT_CONTACT_PROFILESHARE: 'Share profile',
    OVERVIEW_EDIT_CONTACT_GENERATE_TOKEN: 'Generate',
    OVERVIEW_EDIT_CONTACT_RESET_TOKEN: 'Reset',
    OVERVIEW_EDIT_CONTACT_TOKEN_INFO: 'Sharing profile URL\'s will only work if WhatsSpy Public is available from the internet.',
    OVERVIEW_EDIT_CONTACT_TOKEN_INFO2: 'Click on the token to copy the link. The generation of tokens does not have to be saved.',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS: 'Notifications',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_ONLINE: 'Coming online',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_STATUSMSG: 'Status message change',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_PROFPIC: 'Profile picture change',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_PRIV: 'Privacy setting changes',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_AGENTS: 'There are no notification agents configured in',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_AGENTS_CONFIG: 'config.php',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_MISSING: 'Check config.example.php in case you are missing these options.',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_SENDING: 'Sending notifications for user actions via',
    OVERVIEW_AND: 'and',
    OVERVIEW_EDIT_CONTACT_SHOW_TIMELINE: 'Show timeline notifications (if open)',
    OVERVIEW_EDIT_CONTACT_SHOW_TIMELINE_EXPL: 'Notification sound used in the timeline for this user.',
    OVERVIEW_EDIT_CONTACT_SAVE: 'Save contact',
    OVERVIEW_EDIT_CONTACT_INACTIVE: 'Set inactive',
    OVERVIEW_EDIT_CONTACT_DELETE: 'Delete contact (!)',
    OVERVIEW_EDIT_CONTACT_DETELE_TITLE: 'Delete all information of this contact, including any status records.',
    OVERVIEW_EDIT_CONTACT_INACTIVE_TITLE: 'Do not track the user, but keep any status/privacy records of this person. This change can take up to an hour to take effect in the tracker.',
    OVERVIEW_GROUPS_H: 'Manage Groups',
    OVERVIEW_GROUPS_EXISTING: 'Existing groups',
    OVERVIEW_GROUPS_USERS: 'Users:',
    OVERVIEW_GROUPS_STATSEN: 'Statistics sharing enabled',
    OVERVIEW_GROUPS_STATSDIS: 'Sharing disabled*',
    OVERVIEW_GROUPS_NONE: 'No groups defined yet...',
    OVERVIEW_GROUPS_SHARE: '* You can share group statistics in the "Statistics" page.',
    OVERVIEW_GROUPS_DELETE: '** Deleting the group will not delete the users in this group.',
    OVERVIEW_GROUPS_DELETEBTN: 'Delete group**',
    OVERVIEW_GROUPS_CREATE: 'Create group',
    OVERVIEW_GROUPS_CREATE_NAME: 'Group name',
    OVERVIEW_GROUPS_CREATEBTN: 'Create group',
    OVERVIEW_GROUPS_PLACEHOLDER: 'name of the group (required)',
    OVERVIEW_GROUPS_CLOSE: 'Close',
    OVERVIEW_PERFORMANCE_H: 'Manage User Interface Performance',
    OVERVIEW_PERFORMANCE_TIMELINE: 'Account timeline',
    OVERVIEW_PERFORMANCE_TIMELINE_OPTION: 'Display history:',
    OVERVIEW_PERFORMANCE_TIMELINE_EXP: 'This setting has a',
    OVERVIEW_PERFORMANCE_TIMELINE_EXP2: 'big',
    OVERVIEW_PERFORMANCE_TIMELINE_EXP3: 'performance impact when you (re)load a users timeline. This affects the overview, compare and shared profile page.',
    OVERVIEW_PERFORMANCE_TRACKER_H: 'Tracker sessions',
    OVERVIEW_PERFORMANCE_TRACKER_OPTION: 'Display in timeline',
    OVERVIEW_PERFORMANCE_TRACKER_EXP: 'This setting has a',
    OVERVIEW_PERFORMANCE_TRACKER_EXP2: 'small',
    OVERVIEW_PERFORMANCE_TRACKER_EXP3: 'performance impact when you (re)load a users timeline. This affects both the overview and compare page.',
    OVERVIEW_PERFORMANCE_SAVE: 'Save settings',
    OVERVIEW_PERFORMANCE_CLOSE: 'Close',
    COMPARE_SELECT: 'Select candidate(s)',
    COMPARE_ADD_TO_COMPARE: 'Add user to comparison',
    COMPARE_ADD: 'Add',
    COMPARE_ADD_GROUP_COMPARE: 'Add group to comparison',
    COMPARE_ADD_NOTICE: 'Loading large groups may cause a temporary browser freeze due to the vast amount of information.',
    COMPARE_CURR_LIST: 'Current candidates in the comparison:',
    COMPARE_CURR_LIST_INFO: 'Candidate / Privacy settings',
    COMPARE_LASTSEEN: 'last seen :',
    COMPARE_STATUSMSG: 'status messages :',
    COMPARE_PROFPIC: 'profile pic :',
    COMPARE_REMOVE: 'Remove',
    COMPARE_LOADING: 'Loading account information ...',
    COMPARE_CONTACTS: 'contacts*',
    COMPARE_EVERYBODY: 'everyone',
    COMPARE_CONTACTS_NOTICE: 'This privacy setting may be contacts or nobody. This can\'t be detected.',
    STATS_TOKEN_INFO: 'You are not allowed to view this group because the token is or became invalid.',
    STATS_TOKEN_GROUP: 'Shared group profile:',
    STATS_TOKEN_GROUP_INFO: 'This is a shared statistics report of the group',
    STATS_TOKEN_GROUP_INFO2: 'created by the hoster of this WhatsSpy Public instance.',
    STATS_NO_INFO: 'Not enough information available ...',
    STATS_LOADING: 'Loading information ...',
    STATS_FILTER: 'Filter options',
    STATS_NOTES: 'Notes',
    STATS_INFO_VALIDITY: 'All information on this page does not update. You can refresh by clicking the gray timestamp in "status".',
    STATS_TOKEN_GEN: 'Generate',
    STATS_TOKEN_RESET: 'Reset',
    STATS_SHARE_INFO: 'Sharing this statistics group page URL\'s will only work if WhatsSpy Public is available from the internet. Click on the token to copy the link.',
    STATS_H: 'WhatsSpy Public Statistics',
    STATS_TRACKER_STATUS: 'Tracker status',
    STATS_SESSION: 'Tracker sessions',
    STATS_FIRST_SESSION: 'First tracker session (start of information flow)',
    STATS_DB_CONTENT: 'Database content',
    STATS_NUMBER_OF_ACC: 'Number of accounts',
    STATS_ACCOUNTS: 'accounts',
    STATS_STATUSES: 'statuses',
    STATS_PROFPIC: 'profile pictures',
    STATS_STSMSG: 'status messages',
    STATS_H_ONLINE: 'Online/offline statuses gathered',
    STATS_H_TOTALTIME: 'Total time spent on WhatsApp by all contacts',
    STATS_H_PROFPICSUM: 'Profile pictures gathered',
    STATS_H_STATUSMSGSUM: 'Status messages gathered',
    STATS_H_PRIVACY: 'Privacy awareness',
    STATS_PRIVACY_H: 'Privacy settings of tracked users',
    STATS_PRIVACY_TABLE_TH1: 'Privacy option',
    STATS_PRIVACY_TABLE_TH2: 'contacts/nobody',
    STATS_PRIVACY_TABLE_TH3: 'everyone',
    STATS_PRIVACY_OPTION1: 'Lastseen*',
    STATS_PRIVACY_OPTION2: 'Status messages',
    STATS_PRIVACY_OPTION3: 'Profile pictures',
    STATS_PRIVACY_USERS: 'users',
    STATS_PRIVACY_HISTORY: 'Privacy changes while tracking',
    STATS_PRIVACY_LASTSEEN: 'Lastseen privacy changes',
    STATS_PRIVACY_CHANGE: 'changes',
    STATS_PRIVACY_PROFPIC: 'Profile picture privacy changes',
    STATS_PRIVACY_STATUSMSG: 'Status message privacy changes',
    STATS_PRIVACY_INFO1: '* The lastseen option does not protect you against tracking online/offline statuses. Check this',
    STATS_PRIVACY_INFO2: 'article',
    STATS_PRIVACY_INFO3: 'explaining the problem in detail.',
    STATS_PIE_CHART_ONLINE_TIME_H: 'WhatsApp usage (online time / opening) compared per user',
    STATS_PIE_CHART_TODAY: 'Show today',
    STATS_PIE_CHART_7DAYS: 'Show 7 days',
    STATS_PIE_CHART_14DAYS: 'Show 14 days',
    STATS_PIE_CHART_ALL: 'Show all',
    STATS_PIE_CHART_PIE_OPEN_H_ALL: 'Opening WhatsApp - All',
    STATS_PIE_CHART_PIE_OPEN_H_7DAYS: 'Opening WhatsApp - Last 7 days',
    STATS_PIE_CHART_PIE_OPEN_H_14DAYS: 'Opening WhatsApp - Last 14 days',
    STATS_PIE_CHART_PIE_OPEN_H_TODAY: 'Opening WhatsApp - Today',
    STATS_PIE_CHART_PIE_ONLINE_H_ALL: 'Online time in WhatsApp - All',
    STATS_PIE_CHART_PIE_ONLINE_H_7DAYS: 'Online time in WhatsApp - Last 7 days',
    STATS_PIE_CHART_PIE_ONLINE_H_14DAYS: 'Online time in WhatsApp - Last 14 days',
    STATS_PIE_CHART_PIE_ONLINE_H_TODAY: 'Online time in WhatsApp - Today',
    STATS_PIE_CHART_PIE_INFO: 'Please note that every online session can be off by 0-4 seconds based on WhatsApp, your machine and your network activity. This means all this data is the maximum time they spent on WhatsApp.',
    STATS_PIE_CHART_BAR_H: 'WhatsApp usage (online time / opening) compared per timeunit',
    STATS_PIE_CHART_BAR_OPEN_H_WEEKDAY: 'Opening WhatsApp per weekday',
    STATS_PIE_CHART_BAR_OPEN_H_HOUR: 'Opening WhatsApp per hour',
    STATS_PIE_CHART_BAR_SHOWHOUR: 'Show per hour',
    STATS_PIE_CHART_BAR_SHOWWEEKDAY: 'Show per weekday',
    STATS_PIE_CHART_BAR_TIME_H_WEEKDAY: 'Time on WhatsApp per weekday',
    STATS_PIE_CHART_BAR_TIME_H_HOUR: 'Time on WhatsApp per hour',
    STATS_BAR_CHART_TODAY: 'today',
    STATS_BAR_CHART_7DAYS: '7 days',
    STATS_BAR_CHART_14DAYS: '14 days',
    STATS_BAR_CHART_ALLTIME: 'all time',
    STATS_TOP_H1: 'Top',
    STATS_TOP_H2: 'tracked users',
    STATS_TOP_ALL: 'Show all',
    STATS_TOP_H3: 'most active users per day',
    STATS_TOP_DAYS_AGO: 'days ago',
    STATS_TOP_YESTERDAY: 'Yesterday',
    STATS_TOP_TODAY: 'Today',
    STATS_TOP_TRACKED_CONTACT: 'Tracked contact',
    STATS_TOP_TIME: 'Time online',
    STATS_TOP_OPENED: 'Opened WA',
    STATS_TOP_TIMES: 'times',
    STATS_TOP_H4: 'most active users in total',
    STATS_TOP_ALL: 'All',
    STATS_TOP_DAYS: 'days',
    STATS_TOP_HOURS: 'hours',
    STATS_TYPE_today: 'today',
    STATS_TYPE_yesterday: 'yesterday',
    STATS_TYPE_2days_ago: '2 days ago',
    STATS_TYPE_3days_ago: '3 days ago',
    STATS_TYPE_4days_ago: '4 days ago',
    STATS_TYPE_alltime: 'all time',
    STATS_TYPE_31days: '31 days',
    STATS_TYPE_14days: '14 days',
    STATS_TYPE_7days: '7 days',
    STATS_TYPE_24hours: '24 hours',
    TIMELINE_FILTER: 'Filters',
    TIMELINE_FILTER_PHONE_PLACEHOLDER: 'Search by phone number ...',
    TIMELINE_FILTER_NAME_PLACEHOLDER: 'Use name|name to filter on multiple names.',
    TIMELINE_SEARCH_NAME: 'Search by name ...',
    TIMELINE_INFO_STATUS: 'The system is checking all statuses',
    TIMELINE_INFO_FROM: 'from',
    TIMELINE_INFO_CONTACTS: 'contacts',
    TIMELINE_INFO_CONTINIOUS: 'continuously from',
    TIMELINE_INFO_LASTSTATUS: 'Contacts that have "last seen" set to "nobody" will be',
    TIMELINE_INFO_LASTSTATUS2: 'tracked anyway',
    TIMELINE_INFO_LIVE: 'Unlike the overview and comparison page, this information is live.',
    TIMELINE_FILTER_NOTIFY: 'Notify for any event (with filter)',
    TIMELINE_FILTER_TRACKER: 'Show tracker events',
    TIMELINE_ACTIVITY_H: 'Activity Timeline',
    TIMELINE_STATUS_H: 'Status Timeline',
    TIMELINE_ACTIVITY_TIMESPAN1: 'Activity timeline',
    TIMELINE_ACTIVITY_TIMESPAN2: 'from',
    TIMELINE_ACTIVITY_TIMESPAN3: 'till now',
    TIMELINE_ACTIVITY_TRACKERSTART: 'Tracker is now online',
    TIMELINE_ACTIVITY_TRACKERSTART_STARTED: 'started at',
    TIMELINE_ACTIVITY_TRACKERSTOP: 'Tracker is now offline',
    TIMELINE_ACTIVITY_TRACKERSTOP_SESSION: 'this session lasted from',
    TIMELINE_ACTIVITY_TRACKERSTOP_TILL: 'till',
    TIMELINE_ACTIVITY_TRACKERSTOP_REASON: 'Reason:',
    TIMELINE_ACTIVITY_TRACKERSTOP_SUPPORT: 'Support for common problems',
    TIMELINE_ACTIVITY_STATUSMSG: 'New status message for',
    TIMELINE_ACTIVITY_STATUSMSG_TO: 'changed to',
    TIMELINE_ACTIVITY_PROFPIC: 'New profile photo for',
    TIMELINE_ACTIVITY_PROFPIC_TITLE: 'Detecting profile picture changes can take 0-4 hours.',
    TIMELINE_ACTIVITY_PRIV: 'changed his privacy setting',
    TIMELINE_ACTIVITY_PRIV_OPTION: 'Privacy option',
    TIMELINE_ACTIVITY_PRIV_LASTSEEN: 'last seen',
    TIMELINE_ACTIVITY_PRIV_SETTO: 'is now set to',
    TIMELINE_ACTIVITY_PRIV_CONTACTS: 'contacts*',
    TIMELINE_ACTIVITY_PRIV_EVERYONE: 'everyone',
    TIMELINE_ACTIVITY_PRIV_CONTACTSTITLE: 'This privacy setting may be contacts or nobody. This can\'t be detected.',
    TIMELINE_ACTIVITY_PRIV_PROFPIC: 'profile picture',
    TIMELINE_ACTIVITY_PRIV_STATUSMSG: 'status messages',
    TIMELINE_ACTIVITY_NOINFO: 'No information available ..',
    TIMELINE_ACTIVITY_LOADMORE: 'Click to load 7 more days of older entries ..',
    TIMELINE_STATUS_H: 'Status timeline',
    TIMELINE_STATUS_ONLINE: 'Online from',
    TIMELINE_STATUS_TILL: 'till',
    TIMELINE_STATUS_NOINFO: 'No information available ..',
    TIMELINE_STATUS_NOINFOFILTER: 'No current user statuses for this filter ..',
    ABOUT_LICENSE0: 'WhatsSpy Public is a Proof of Concept to show how broken Whatsapp privacy settings are. With this tool you can basicly follow anyone\'s behaviour with only the knowledge of their phone number. This tool is for Proof of Concept purposes only! Please read the',
    ABOUT_LICENSE1: 'license',
    ABOUT_LICENSE2: 'which applies to this PoC.',
    ABOUT_DONATION0: 'You can support this work by a small donation:',
    ABOUT_DONATION1: 'Bitcoin:',
    ABOUT_DONATION2: 'or via',
    ABOUT_DONATION3: 'Paypal',
    ABOUT_INFO: 'General information',
    ABOUT_VERSION: 'Running version:',
    ABOUT_UPDATE: 'is available.',
    ABOUT_UPTODATE: 'Your version is up to date.',
    ABOUT_UPDATE_NOW: 'Update',
    ABOUT_UPDATE_LOG: 'Updatelog and how-to-update',
    ABOUT_WIKI: 'Wiki home page:',
    ABOUT_WIKI_LINK: 'Gitlab Wiki',
    ABOUT_FAQ: 'FAQ:',
    ABOUT_FAQ_LINK: 'Frequently Asked Questions',
    ABOUT_TROUBLE: 'Troubleshooting:',
    ABOUT_TROUBLE_LINK: 'Troubleshooting',
    ABOUT_OPTIONS: 'Options:',
    ABOUT_OPTIONS_LOGOUT: 'Logout WebUI',
    ABOUT_LANGUAGE: 'Client Language:',
    ABOUT_ADVANCED: 'Advanced options:',
    ABOUT_ADVANCED_STOP: 'Stop tracker',
    ABOUT_ADVANCED_START: 'Start tracker',
    ABOUT_ADVANCED_UPDATE: 'Auto update',
    ABOUT_NEWS: 'Literature/news for this project:',
    ABOUT_AGENTS: 'Notification agents',
    ABOUT_AGENTS_NONE1: 'There are no notification agents configured in',
    ABOUT_AGENTS_NONE2: 'config.php',
    ABOUT_AGENTS_NONE3: 'Check config.example.php in case you are missing these options.',
    ABOUT_AGENTS_PROPS: 'Notifying properties:',
    ABOUT_AGENTS_USER: 'user actions',
    ABOUT_AGENTS_TRACKER: 'tracker actions',
    ABOUT_AGENTS_TO: 'to:',
    ABOUT_AGENTS_RESTART: 'Remember to restart the tracker after any change in your config.php.',
    ABOUT_QA: 'Question and Answers',
    CONTROLLER_TIMELINE_1D: '24 hours (best performance)',
    CONTROLLER_TIMELINE_7D: '7  days',
    CONTROLLER_TIMELINE_14D: '14 days',
    CONTROLLER_TIMELINE_31D: '31 days (slow)',
    CONTROLLER_TIMELINE_90D: '90 days (very slow)',
    CONTROLLER_CHAR_OPENED: 'opened',
    CONTROLLER_CHAR_TIMES: 'times',
    CONTROLLER_CHAR_MINUTES: 'minutes',
    CONTROLLER_COPY: 'Copy to clipboard: Ctrl+C, Enter',
    CONTROLLER_WEEKDAY_Sunday: 'Sunday',
    CONTROLLER_WEEKDAY_Monday: 'Monday',
    CONTROLLER_WEEKDAY_Tuesday: 'Tuesday',
    CONTROLLER_WEEKDAY_Wednesday: 'Wednesday',
    CONTROLLER_WEEKDAY_Thursday: 'Thursday',
    CONTROLLER_WEEKDAY_Friday: 'Friday',
    CONTROLLER_WEEKDAY_Saturday: 'Saturday',
    CONTROLLER_NONAME: 'No name',
    CONTROLLER_NOTOKEN: 'Not shared ...',
    CONTROLLER_TRACKER_REASON_NONE: 'not given',
    CONTROLLER_TIME_DAY: 'd',
    CONTROLLER_TIME_HOURS: 'h',
    CONTROLLER_TIME_MINUTES: 'min',
    CONTROLLER_TIME_SECONDS: 'sec',
    CONTROLLER_SERVER_NO_RES: 'Could not contact the server.',
    CONTROLLER_GROUP_NEW: 'Enter the new name for this group:',
    CONTROLLER_ACCOUNT_DEL: 'Are you sure you want to delete this Account?',
    CONTROLLER_ACCOUNT_REMOVED: ' removed!',
    CONTROLLER_ACCOUNT_UPDATED: 'Contact updated',
    CONTROLLER_ACCOUNT_ADDED: 'Contact added to WhatsSpy. Tracking will start in 5-10 minutes.',
    CONTROLLER_ACCOUNT_INACTIVE: ' set inactive!',
    CONTROLLER_GROUP_SAVE: 'Saved new groupname!',
    CONTROLLER_GROUP_ADD: 'New group added.',
    CONTROLLER_GROUP_DEL: 'Group removed.',
    CONTROLLER_CONFIG_UPDATE: 'Configuration updated',
    CONTROLLER_TIME_DAY_FULL: 'day',
    CONTROLLER_TIME_WEEK_FULL: 'week',
    CONTROLLER_TIME_MONTH_FULL: 'month',
    CONTROLLER_TIME_CUSTOM_FULL: 'custom',
    CONTROLLER_TIMELINE_HISTORY: 'History view:',
    CONTROLLER_TIMELINE_DAYS: 'day(s)',
    CONTROLLER_TIMELINE_ONLINE: 'Online',
    CONTROLLER_TIMELINE_DURATION: 'Duration:',
    CONTROLLER_COMPARISON_ALREADY_IN: ' is already in the comparison!',
    CONTROLLER_NOTIFICATION_ONLINE: ' is now online.',
    CONTROLLER_NOTIFICATION_STATUSMSG: ' has a new status message: ',
    CONTROLLER_NOTIFICATION_PROFPIC: ' has a new profile picture.',
    CONTROLLER_NOTIFICATION_PIRV_EVERY: 'everybody',
    CONTROLLER_NOTIFICATION_PRIV_CONTACTS: 'contacts or nobody',
    CONTROLLER_NOTIFICATION_PRIV_LASTSEEN: ' has changed his last seen privacy setting to ',
    CONTROLLER_NOTIFICATION_PRIV_PROFPIC: ' has changed his profile picture privacy setting to ',
    CONTROLLER_NOTIFICATION_PRIV_STATUSMSG: ' has changed his status message privacy setting to ',
    CONTROLLER_NOTIFICATION_TRACKER_START: 'Tracker has started tracking.',
    CONTROLLER_NOTIFICATION_TRACKER_STOP: 'Tracker has stopped tracking with reason: ',
    CONTROLLER_STAT_TIMES: 'times',
    CONTROLLER_CMD0: 'CMD: ',
    CONTROLLER_CMD1: ' resulted in code: ',
    CONTROLLER_CMD2: ' with output: '
    });
    moment.locale('en', {
        months : [
            "January", "February", "March", "April", "May", "June", "July",
            "August", "September", "October", "November", "December"
        ],
        monthsShort : [
            "Jan", "Feb", "Mar", "Apr", "May", "Jun",
            "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
        ],
        weekdays : [
            "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
        ],
        weekdaysShort : [
            "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"
        ],
        longDateFormat : {
            LT: "h:mm A",
            LTS: "h:mm:ss A",
            L: "MM/DD/YYYY",
            l: "M/D/YYYY",
            LL: "MMMM Do YYYY",
            ll: "MMM D YYYY",
            LLL: "MMMM Do YYYY LT",
            lll: "MMM D YYYY LT",
            LLLL: "dddd, MMMM Do YYYY LT",
            llll: "ddd, MMM D YYYY LT"
        },
        relativeTime : {
            future: "in %s",
            past:   "%s ago",
            s:  "seconds",
            m:  "a minute",
            mm: "%d minutes",
            h:  "an hour",
            hh: "%d hours",
            d:  "a day",
            dd: "%d days",
            M:  "a month",
            MM: "%d months",
            y:  "a year",
            yy: "%d years"
        }
    });

    $translateProvider.translations('es', {
    /* PLEASE NOTE that spaces etc. are all of importance here. You also must escape ' (by using \') */
    /* Traduccion al español por Javier Andres Tolosa Rivera  Colombia */
    TRANSLATOR: 'Javier Andres Tolosa Rivera',
    MENU_LOGIN: 'Iniciar Sesion',
    MENU_OVERVIEW: 'Info General',
    MENU_COMPARE: 'Comparar',
    MENU_TIMELINE: 'Cronologia',
    MENU_STATS: 'Estadisticas',
    MENU_ABOUT: 'Ayuda',
    MENU_USER: 'Usuario Publico',
    MENU_GROUP: 'Grupo Publico',
    MENU_LOADING: 'Cargando Datos Nuevos ...',
    MENU_STATUS: 'Estado',
    MENU_TRACKER_ONLINE: 'Rastreador en linea',
    MENU_TRACKER_OFFLINE: 'Rastreador Apagado',
    MENU_TRACKER_NOAUTH: 'No Autenticado',
    MENU_TRACKER_USERS: 'Usuarios',
    MENU_TRACKER_REFRESH: 'Haga clic aqui para actualizar los datos cargados en la web-app.',
    MENU_POC: 'Prueba de Concepto',
    FOOTER_VERSION: 'Version',
    FOOTER_V_BEHIND: 'Desactualizada',
    LOGIN_WELCOME: 'Bienvenido!',
    LOGIN_WELCOME_MSG: 'Bienvenido a WhatsSpy PoC Publico ! Antes de iniciar el seguimiento por favor lea la',
    LOGIN_LICENSE: 'Licencia',
    LOGIN_LOGIN_HEAD: 'Iniciar Sesion',
    LOGIN_AUTH_NOTIFY: 'Parece que no se ha autenticado. Inicie sesion para ver y administrar el rastreador.',
    LOGIN_PASS_FIELD: 'Clave',
    LOGIN_SIGN_IN_BTN: 'Registrarse',
    LOGIN_RESET_BTN: 'Reiniciar',
    LOGIN_PASS_PLACEHOLDER: 'Clave ...',
    TOKEN_INVALID: 'Ficha Invalida:',
    OVERVIEW_TOKEN_INVALID: 'No tienes permiso para ver este usuario porque el token no es valido.',
    OVERVIEW_TOKEN_INFO_STRONG: 'Perfil de Usuario Compartido:',
    OVERVIEW_TOKEN_INFO: 'Este es un perfil de usuario compartido creado por el proveedor de alojamiento en esta Instancia WhatsSpy publico. La linea de tiempo contiene solo una instantanea de los ultimos estados.',
    OVERVIEW_FILTERS: 'Filtros',
    OVERVIEW_FILTER_PHONE: 'Buscar por numero de telefono ...',
    OVERVIEW_FILTER_NAME_TITLE: 'Use el nombre | para filtrar en multiples nombres.',
    OVERVIEW_FILTER_NAME: 'Buscar por Nombre ...',
    OVERVIEW_INFO_STATUS: 'El Sistema Esta Comprobando Todos los Estados',
    OVERVIEW_INFO_STATUS_FROM: 'De',
    OVERVIEW_INFO_STATUS_CONTACTS: 'Contactos',
    OVERVIEW_INFO_STATUS_SINCE: 'Desde',
    OVERVIEW_INFO_PRIV: 'Contactos que han configurado "vista por ultima vez" para no ser visto por "nadie" seran',
    OVERVIEW_INFO_PRIV_LINK: 'Seguidos de Todos Modos',
    OVERVIEW_INFO_LIVE: 'La informacion de esta pagina no es online, puede volver a cargar esta pagina haciendo clic en la marca de tiempo gris en el panel de "Estado".',
    OVERVIEW_INFO_TIMESPAN: 'Al lado de la linea de tiempo, toda la informacion es de desde que comenzo el seguimiento de este contacto (Salvo se Indique lo Contrario).',
    OVERVIEW_INFO_VERIFY: 'Contactos se Verificaran Dentro de 5-10 Minutos',
    OVERVIEW_INFO_RELOAD: 'Recargar Datos',
    OVERVIEW_INFO_RELOAD_2: 'Para Comprobar de Nuevo.',
    OVERVIEW_ADD: 'Agregar Contacto',
    OVERVIEW_IMPORT: 'Importarlos de Google',
    OVERVIEW_MANAGE_GROUPS: 'Administrar Grupos',
    OVERVIEW_MANAGE_PERF: 'Opciones de Rendimiento',
    OVERVIEW_EXPAND: 'Expandir Vista',
    OVERVIEW_COLLAPSE: 'Contraer Vista',
    OVERVIEW_EDIT: 'Editar',
    OVERVIEW_CONTACT_SINCE: 'Seguimiento Desde',
    OVERVIEW_CONTACT_LASTSEEN: 'Ultima Vista',
    OVERVIEW_CONTACT_NOTIF: 'Notificaciones Habilitadas',
    OVERVIEW_CONTACT_SHARING: 'Compartir Perfil Habilitado',
    OVERVIEW_NO_INFO: 'No hay Informacion Disponible ..',
    OVERVIEW_CLICK_LOAD: 'Clic Para Cargar Datos',
    OVERVIEW_CLICK_LOAD_TIMELINE: 'Cargar linea de Tiempo',
    OVERVIEW_CONTACT_H_ANALYTICS: 'Analisis / Informacion',
    OVERVIEW_CONTACT_ANALYTICS_OVERVIEW: 'Descripcion General',
    OVERVIEW_CONTACT_ANALYTICS_OPENOVERVIEW: 'Vision General Abierta',
    OVERVIEW_CONTACT_ANALYTICS_TIME_OVERVIEW: 'Resumen de Tiempo',
    OVERVIEW_CONTACT_ANALYTICS_STATUS: 'Mensajes de Estado',
    OVERVIEW_CONTACT_ANALYTICS_PICS: 'Fotos de Perfil',
    OVERVIEW_CONTACT_OPENED_H: 'Cliente WhatsApp Iniciado',
    OVERVIEW_CONTACT_TABLE_1D: '(24h) Hoy',
    OVERVIEW_CONTACT_TABLE_7D: '(07d) Los Ultimos 7 Dias',
    OVERVIEW_CONTACT_TABLE_14D: '(14d) Ultimas Dos Semanas',
    OVERVIEW_CONTACT_TABLE_31D: '(31d) El Mes Pasado',
    OVERVIEW_CONTACT_TABLE_xD: '(---) Todo El Tiempo',
    OVERVIEW_CONTACT_TRACKING_SINCE: 'Seguimiento Desde',
    OVERVIEW_CONTACT_TIME_SPENT_WA: 'El Tiempo Dedicado a WhatsApp',
    OVERVIEW_CONTACT_LOADING_INFO: 'Cargando Informacion ...',
    OVERVIEW_CONTACT_SWITCH_HOUR_VIEW: 'Mostrar por Hora',
    OVERVIEW_CONTACT_SWITCH_WEEKDAY_VIEW: 'Mostrar por dia de la Semana',
    OVERVIEW_CONTACT_H_OPENING_WA_WEEKDAY: 'Apertura de WhatsApp por dia de la Semana',
    OVERVIEW_CONTACT_H_OPENING_WA_HOUR: 'Apertura de WhatsApp por Hora',
    OVERVIEW_CONTACT_H_TIME_WA_WEEKDAY: 'Tiempo en WhatsApp por dia de la Semana',
    OVERVIEW_CONTACT_H_TIME_WA_HOUR: 'Tiempo en WhatsApp por Hora',
    OVERVIEW_CONTACT_H_PRIV_STATUS: 'Privacidad / Estado Online',
    OVERVIEW_CONTACT_PRIV_STATUS: 'Privacidad',
    OVERVIEW_CONTACT_ONLINE_EVENTS: 'Eventos en Linea',
    OVERVIEW_CONTACT_H_LASTSEEN: 'Ultima Vista',
    OVERVIEW_PRIVACY_SETTINGS_PUBLIC: 'Todos',
    OVERVIEW_PRIVACY_SETTINGS_FRIENDS: 'Contactos*',
    OVERVIEW_PRIVACY_LAST_CHANGE: 'Cambiado a',
    OVERVIEW_PRIVACY_LAST_CHANGE_AT: 'a',
    OVERVIEW_PRIVACY_H_PROF_PIC: 'Foto de Perfil',
    OVERVIEW_PRIVACY_H_STATUS: 'Mensajes de Estado',
    OVERVIEW_PRIVACY_TRACK_NOTICE: 'Imagen de Perfil y Mensaje de Estado son Revisados Cada 2 Horas.',
    OVERVIEW_PRIVACY_ASSUMPTION: 'Suponiendo que este Usuario no tiene el Numero de Seguimiento en su lista de Contactos. Si este es el caso \'Solo Contactos\' Se Interpretara Como \'Todos\' en Esta Vista.',
    OVERVIEW_LOG_FROM: 'Desde',
    OVERVIEW_LOG_TILL: 'Hasta',
    OVERVIEW_LOG_NOW: 'Ahora',
    OVERVIEW_NO_ACC: 'No hay Cuentas de Seguimiento ..',
    OVERVIEW_ADD_CONTACT_H: 'Agregar Contacto por Telefono',
    OVERVIEW_ADD_CONTACT_PHONE: 'Numero de Telefono',
    OVERVIEW_ADD_CONTACT_PLACEHOLDER_COUNTRYCODE: 'Codigo de Pais ...',
    OVERVIEW_ADD_CONTACT_PLACEHOLDER_PHONE: 'Numero de Telefono ...',
    OVERVIEW_ADD_CONTACT_NAME: 'Nombre de Contacto',
    OVERVIEW_ADD_CONTACT_GROUP: 'Grupos',
    OVERVIEW_ADD_CONTACT_NOTICE: 'El nuevo contacto sera verificado como usuario de WhatsApp y agregado al  rastreador dentro de 5-10 minutos. Despues de esto se puede encontrar el contacto en la lista de resumen.',
    OVERVIEW_ADD_CONTACT_ADD: 'Agregar Contacto',
    OVERVIEW_ADD_CONTACT_CLOSE: 'Cerrar',
    OVERVIEW_EDIT_CONTACT_H: 'Editar Nombre Contacto',
    OVERVIEW_EDIT_CONTACT_PHONE: 'Numero de Telefono',
    OVERVIEW_EDIT_CONTACT_NAME: 'Nombre de Contacto',
    OVERVIEW_EDIT_CONTACT_NAME_PLACEHOLDER: '(opcional) Nombre de Contacto',
    OVERVIEW_EDIT_CONTACT_GROUPS: 'Grupos',
    OVERVIEW_EDIT_CONTACT_PROFILESHARE: 'Compartir el Perfil',
    OVERVIEW_EDIT_CONTACT_GENERATE_TOKEN: 'Generar',
    OVERVIEW_EDIT_CONTACT_RESET_TOKEN: 'Reiniciar',
    OVERVIEW_EDIT_CONTACT_TOKEN_INFO: 'Compartir el perfil por URL solo funcionara si WhatsSpy Publico esta disponible en la internet.',
    OVERVIEW_EDIT_CONTACT_TOKEN_INFO2: 'Haga clic en la ficha para copiar el enlace. La generacion de fichas no tiene que ser guardada.',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS: 'Notificaciones',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_ONLINE: 'Proximamente en linea',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_STATUSMSG: 'Cambiar Mensaje de Estado',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_PROFPIC: 'Cambiar Foto de Perfil',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_PRIV: 'Cambios en Configuracion de Privacidad',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_AGENTS: 'No Hay Agentes de Notificacion Configurados en',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_AGENTS_CONFIG: 'config.php',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_MISSING: 'Compruebe config.example.php en caso de que hagan falta estas opciones.',
    OVERVIEW_EDIT_CONTACT_NOTIFICATIONS_SENDING: 'Envio de notificaciones de acciones del usuario a traves de',
    OVERVIEW_AND: 'y',
    OVERVIEW_EDIT_CONTACT_SHOW_TIMELINE: 'Mostrar notificaciones linea de tiempo (Si Esta Abierto)',
    OVERVIEW_EDIT_CONTACT_SHOW_TIMELINE_EXPL: 'Sonido de notificacion utilizado en linea de tiempo para este usuario.',
    OVERVIEW_EDIT_CONTACT_SAVE: 'Guardar Contacto',
    OVERVIEW_EDIT_CONTACT_INACTIVE: 'Conjunto Inactivo',
    OVERVIEW_EDIT_CONTACT_DELETE: 'Borrar Bontacto (!)',
    OVERVIEW_EDIT_CONTACT_DETELE_TITLE: 'Eliminar toda la informacion de este contacto, incluyendo los registros de estado.',
    OVERVIEW_EDIT_CONTACT_INACTIVE_TITLE: 'No realizar el seguimiento del usuario, pero mantener registros de estado / de privacidad de esta persona. Este cambio puede tardar hasta una hora para entrar en vigor en el rastreador.',
    OVERVIEW_GROUPS_H: 'Administrar Grupos',
    OVERVIEW_GROUPS_EXISTING: 'Grupos Existentes',
    OVERVIEW_GROUPS_USERS: 'Usuarios:',
    OVERVIEW_GROUPS_STATSEN: 'Compartir Estadisticas Habilitado',
    OVERVIEW_GROUPS_STATSDIS: 'Compartiendo Deshabilitado*',
    OVERVIEW_GROUPS_NONE: 'No hay Grupos aun por Definir...',
    OVERVIEW_GROUPS_SHARE: '* Puede compartir estadisticas de grupo en la pagina "Estadisticas".',
    OVERVIEW_GROUPS_DELETE: '** Eliminacion del grupo no borrara los usuarios en este grupo.',
    OVERVIEW_GROUPS_DELETEBTN: 'Eliminar Grupo**',
    OVERVIEW_GROUPS_CREATE: 'Crear Grupo',
    OVERVIEW_GROUPS_CREATE_NAME: 'Nombre del Grupo',
    OVERVIEW_GROUPS_CREATEBTN: 'Crear Grupo',
    OVERVIEW_GROUPS_PLACEHOLDER: 'Nombre del Grupo (Necesario)',
    OVERVIEW_GROUPS_CLOSE: 'Cerrar',
    OVERVIEW_PERFORMANCE_H: 'Gestionar el Rendimiento de Interfaz de Usuario',
    OVERVIEW_PERFORMANCE_TIMELINE: 'Tiempo de Cuenta',
    OVERVIEW_PERFORMANCE_TIMELINE_OPTION: 'Mostrar Historia:',
    OVERVIEW_PERFORMANCE_TIMELINE_EXP: 'Este Ajuste Tiene un',
    OVERVIEW_PERFORMANCE_TIMELINE_EXP2: 'Gran',
    OVERVIEW_PERFORMANCE_TIMELINE_EXP3: 'Impacto en el rendimiento cuando se (re) carga una linea de tiempo a los usuarios. Esto afecta la informacion general, comparar y pagina de perfil compartido.',
    OVERVIEW_PERFORMANCE_TRACKER_H: 'Sesiones del Rastreador',
    OVERVIEW_PERFORMANCE_TRACKER_OPTION: 'Vista en Linea de Tiempo',
    OVERVIEW_PERFORMANCE_TRACKER_EXP: 'Este Ajuste Tiene un',
    OVERVIEW_PERFORMANCE_TRACKER_EXP2: 'Minimo',
    OVERVIEW_PERFORMANCE_TRACKER_EXP3: 'Impacto en el Rendimiento Cuando se (re) Carga una Linea de Tiempo a los Usuarios. Esto Afecta Tanto a la Vision General y Comparacion de la Pagina.',
    OVERVIEW_PERFORMANCE_SAVE: 'Guardar Ajustes',
    OVERVIEW_PERFORMANCE_CLOSE: 'Cerrar',
    COMPARE_SELECT: 'Seleccione Candidato(s)',
    COMPARE_ADD_TO_COMPARE: 'Agregar Usuario a la Comparacion',
    COMPARE_ADD: 'Agregar',
    COMPARE_ADD_GROUP_COMPARE: 'Agregar Grupo de Comparacion',
    COMPARE_ADD_NOTICE: 'Cargar Grupos Grandes Puede Causar un Congelamiento Temporal  en el Navegador Debido a la Gran Cantidad de Informacion.',
    COMPARE_CURR_LIST: 'Candidatos Actuales en la Comparacion:',
    COMPARE_CURR_LIST_INFO: 'Ajustes Candidato / Privacidad',
    COMPARE_LASTSEEN: 'Ultima Vista :',
    COMPARE_STATUSMSG: 'Mensajes de Estado :',
    COMPARE_PROFPIC: 'Foto de Perfil :',
    COMPARE_REMOVE: 'Eliminar',
    COMPARE_LOADING: 'Cargando Informacion de Cuenta ...',
    COMPARE_CONTACTS: 'Contactos*',
    COMPARE_EVERYBODY: 'Todos',
    COMPARE_CONTACTS_NOTICE: 'Esta configuracion de privacidad puede ser contactos o nadie. Esto no puede ser detectado.',
    STATS_TOKEN_INFO: 'No tienes permiso para ver este grupo porque el token no es valido.',
    STATS_TOKEN_GROUP: 'Perfil de Grupo Compartido:',
    STATS_TOKEN_GROUP_INFO: 'Se trata de un informe de estadisticas compartida del grupo',
    STATS_TOKEN_GROUP_INFO2: 'Creado por el proveedor de esta instancia WhatsSpy Publico.',
    STATS_NO_INFO: 'No hay suficiente Informacion Disponible ...',
    STATS_LOADING: 'Cargando Informacion ...',
    STATS_FILTER: 'Opciones de Filtro',
    STATS_NOTES: 'Notas',
    STATS_INFO_VALIDITY: 'Toda la informacion en esta pagina no se actualiza. Puede actualizarla haciendo clic en la marca de tiempo gris "Estado".',
    STATS_TOKEN_GEN: 'Generar',
    STATS_TOKEN_RESET: 'Reiniciar',
    STATS_SHARE_INFO: 'Compartir el perfil por URL solo funcionara si WhatsSpy Publico esta disponible en la internet.Haga clic en la Ficha Para Copiar el Enlace.',
    STATS_H: 'Estadisticas de WhatsSpy Publico',
    STATS_TRACKER_STATUS: 'Estado del Rastreador',
    STATS_SESSION: 'Sesiones del Rastreador',
    STATS_FIRST_SESSION: 'Primera Sesion de Seguimiento (Inicio del flujo de Informacion)',
    STATS_DB_CONTENT: 'Contenido Base de Datos',
    STATS_NUMBER_OF_ACC: 'Numero de Cuentas',
    STATS_ACCOUNTS: 'Cuentas',
    STATS_STATUSES: 'Estados',
    STATS_PROFPIC: 'Fotos de Perfil',
    STATS_STSMSG: 'Mensajes de Estado',
    STATS_H_ONLINE: 'Se reunieron Estados en linea / fuera de linea',
    STATS_H_TOTALTIME: 'El tiempo total gastado en WhatsApp por todos los contactos',
    STATS_H_PROFPICSUM: 'Fotos de Perfil Obtenidas',
    STATS_H_STATUSMSGSUM: 'Mensajes de Estado Obtenidos',
    STATS_H_PRIVACY: 'Conciencia de Privacidad',
    STATS_PRIVACY_H: 'Configuracion de Privacidad de Usuarios Rastreados',
    STATS_PRIVACY_TABLE_TH1: 'Opcion de Privacidad',
    STATS_PRIVACY_TABLE_TH2: 'Contactos /o Nadie',
    STATS_PRIVACY_TABLE_TH3: 'Todos',
    STATS_PRIVACY_OPTION1: 'Ultima Vista*',
    STATS_PRIVACY_OPTION2: 'Mensajes de Estado',
    STATS_PRIVACY_OPTION3: 'Fotos de Perfil',
    STATS_PRIVACY_USERS: 'Usuarios',
    STATS_PRIVACY_HISTORY: 'Cambios Privacidad Durante el Seguimiento',
    STATS_PRIVACY_LASTSEEN: 'Cambios de Privacidad en Ultima Vista',
    STATS_PRIVACY_CHANGE: 'Cambios',
    STATS_PRIVACY_PROFPIC: 'Cambios de Privacidad en Foto de Perfil',
    STATS_PRIVACY_STATUSMSG: 'Cambio la Privacidad del Mensaje de Estado',
    STATS_PRIVACY_INFO1: '* La opcion visto por Ultima vez no lo protege contra el Seguimiento en los estados en linea / o Fuera de linea. Mira Esto',
    STATS_PRIVACY_INFO2: 'Articulo',
    STATS_PRIVACY_INFO3: 'Explicando el Problema en Detalle.',
    STATS_PIE_CHART_ONLINE_TIME_H: 'Uso de WhatsApp (Tiempo en linea / Apertura) Comparacion por Usuario',
    STATS_PIE_CHART_TODAY: 'Mostrar Hoy',
    STATS_PIE_CHART_7DAYS: 'Mostrar 7 Dias',
    STATS_PIE_CHART_14DAYS: 'Mostrar 14 Dias',
    STATS_PIE_CHART_ALL: 'Mostar Todo',
    STATS_PIE_CHART_PIE_OPEN_H_ALL: 'Apertura WhatsApp - Todo',
    STATS_PIE_CHART_PIE_OPEN_H_7DAYS: 'Apertura WhatsApp - Ultimos 7 Dias',
    STATS_PIE_CHART_PIE_OPEN_H_14DAYS: 'Apertura WhatsApp  - Ultimos 14 Dias',
    STATS_PIE_CHART_PIE_OPEN_H_TODAY: 'Apertura WhatsApp - Hoy',
    STATS_PIE_CHART_PIE_ONLINE_H_ALL: 'Tiempo de conexion en WhatsApp - Todos',
    STATS_PIE_CHART_PIE_ONLINE_H_7DAYS: 'Tiempo de Conexion en WhatsApp - Ultimos 7 Dias',
    STATS_PIE_CHART_PIE_ONLINE_H_14DAYS: 'Tiempo de conexion en WhatsApp - Ultimos 14 Dias',
    STATS_PIE_CHART_PIE_ONLINE_H_TODAY: 'Tiempo de conexion en WhatsApp - Hoy',
    STATS_PIE_CHART_PIE_INFO: 'Tenga en cuenta que todas las sesiones en linea pueden ser apagadas por 0-4 segundos en WhatsApp, su maquina y su actividad en la red. Esto significa que todos estos datos es el tiempo maximo que gastaron en WhatsApp.',
    STATS_PIE_CHART_BAR_H: 'Uso deWhatsApp (tiempo en linea / apertura) en comparacion por unidad Tiempo',
    STATS_PIE_CHART_BAR_OPEN_H_WEEKDAY: 'WhatsApp Apertura por dia de la Semana',
    STATS_PIE_CHART_BAR_OPEN_H_HOUR: 'WhatsApp Apertura por Hora',
    STATS_PIE_CHART_BAR_SHOWHOUR: 'Mostrar por Hora',
    STATS_PIE_CHART_BAR_SHOWWEEKDAY: 'Mostrar por dia de la Semana',
    STATS_PIE_CHART_BAR_TIME_H_WEEKDAY: 'Tiempo en WhatsApp por dia de la Semana',
    STATS_PIE_CHART_BAR_TIME_H_HOUR: 'Tiempo en WhatsApp por hora',
    STATS_BAR_CHART_TODAY: 'Hoy',
    STATS_BAR_CHART_7DAYS: '7 dias',
    STATS_BAR_CHART_14DAYS: '14 dias',
    STATS_BAR_CHART_ALLTIME: 'Todo el Tiempo',
    STATS_TOP_H1: 'Top',
    STATS_TOP_H2: 'Usuarios Rastreados',
    STATS_TOP_ALL: 'Mostrar Todo',
    STATS_TOP_H3: 'La Mayoria de Usuarios activos al dia',
    STATS_TOP_DAYS_AGO: 'Dias Atras',
    STATS_TOP_YESTERDAY: 'Ayer',
    STATS_TOP_TODAY: 'Hoy',
    STATS_TOP_TRACKED_CONTACT: 'Contacto Rastreado',
    STATS_TOP_TIME: 'Tiempo en linea',
    STATS_TOP_OPENED: 'Apertura de WA',
    STATS_TOP_TIMES: 'Veces',
    STATS_TOP_H4: 'Mayoria de Usuarios Activos en Total',
    STATS_TOP_ALL: 'Todo',
    STATS_TOP_DAYS: 'Dias',
    STATS_TOP_HOURS: 'Horas',
    STATS_TYPE_today: 'hoy',
    STATS_TYPE_yesterday: 'ayer',
    STATS_TYPE_2days_ago: '2 dias atras',
    STATS_TYPE_3days_ago: '3 dias atras',
    STATS_TYPE_4days_ago: '4 dias atras',
    STATS_TYPE_alltime: 'todo el tiempo',
    STATS_TYPE_31days: '31 dias',
    STATS_TYPE_14days: '14 dias',
    STATS_TYPE_7days: '7 dias',
    STATS_TYPE_24hours: '24 horas',
    TIMELINE_FILTER: 'Filtros',
    TIMELINE_FILTER_PHONE_PLACEHOLDER: 'Bucar por Numero de Telefono ...',
    TIMELINE_FILTER_NAME_PLACEHOLDER: 'Use el nombre | para filtrar en multiples nombres.',
    TIMELINE_SEARCH_NAME: 'Buscar por Nombre ...',
    TIMELINE_INFO_STATUS: 'El Sistema esta Comprobando Todos los Estados',
    TIMELINE_INFO_FROM: 'De',
    TIMELINE_INFO_CONTACTS: 'Contactos',
    TIMELINE_INFO_CONTINIOUS: 'Continuamente Desde',
    TIMELINE_INFO_LASTSTATUS: 'Contactos que Configuraron "visto por Ultima vez" a no ser Vistos por "nadie" Seran',
    TIMELINE_INFO_LASTSTATUS2: 'Seguidos de Todos Modos',
    TIMELINE_INFO_LIVE: 'A diferencia de la pagina de informacion y comparacion, esta informacion es online.',
    TIMELINE_FILTER_NOTIFY: 'Notificar para cualquier evento (con filtro)',
    TIMELINE_FILTER_TRACKER: 'Mostrar Eventos de Seguimiento',
    TIMELINE_ACTIVITY_H: 'Cronograma de Actividad',
    TIMELINE_STATUS_H: 'Estado de Tiempo',
    TIMELINE_ACTIVITY_TIMESPAN1: 'Actividad linea de Tiempo',
    TIMELINE_ACTIVITY_TIMESPAN2: 'Desde',
    TIMELINE_ACTIVITY_TIMESPAN3: 'Hasta Ahora',
    TIMELINE_ACTIVITY_TRACKERSTART: 'Rastreador en linea',
    TIMELINE_ACTIVITY_TRACKERSTART_STARTED: 'Comenzo en',
    TIMELINE_ACTIVITY_TRACKERSTOP: 'Rastreador Apagado',
    TIMELINE_ACTIVITY_TRACKERSTOP_SESSION: 'Esta Sesion se Mantuvo Desde',
    TIMELINE_ACTIVITY_TRACKERSTOP_TILL: 'Hasta',
    TIMELINE_ACTIVITY_TRACKERSTOP_REASON: 'Causa:',
    TIMELINE_ACTIVITY_TRACKERSTOP_SUPPORT: 'Apoyo a Problemas Comunes',
    TIMELINE_ACTIVITY_STATUSMSG: 'Nuevo Mensaje de Estado Para',
    TIMELINE_ACTIVITY_STATUSMSG_TO: 'Cambiado a',
    TIMELINE_ACTIVITY_PROFPIC: 'Nueva Foto de Perfil Para',
    TIMELINE_ACTIVITY_PROFPIC_TITLE: 'Detectar Cambios de Imagen de Perfil Puede Tardar 0-4 Horas.',
    TIMELINE_ACTIVITY_PRIV: 'Cambio su Configuracion de Privacidad',
    TIMELINE_ACTIVITY_PRIV_OPTION: 'Opcion de Privacidad',
    TIMELINE_ACTIVITY_PRIV_LASTSEEN: 'Ultima Vista',
    TIMELINE_ACTIVITY_PRIV_SETTO: 'Esta Ahora Establecido en',
    TIMELINE_ACTIVITY_PRIV_CONTACTS: 'Contactos*',
    TIMELINE_ACTIVITY_PRIV_EVERYONE: 'Todos',
    TIMELINE_ACTIVITY_PRIV_CONTACTSTITLE: 'Esta configuracion de privacidad puede ser a contactos o nadie. Esto no puede ser detectado.',
    TIMELINE_ACTIVITY_PRIV_PROFPIC: 'Foto de Perfil',
    TIMELINE_ACTIVITY_PRIV_STATUSMSG: 'Mensajes de Estado',
    TIMELINE_ACTIVITY_NOINFO: 'No hay Informacion Disponible ..',
    TIMELINE_ACTIVITY_LOADMORE: 'Click Para Cargar 7 Dias de Entradas Antiguas ..',
    TIMELINE_STATUS_H: 'Estado de Tiempo',
    TIMELINE_STATUS_ONLINE: 'Online Desde',
    TIMELINE_STATUS_TILL: 'Hasta',
    TIMELINE_STATUS_NOINFO: 'No hay Informacion Disponible ..',
    TIMELINE_STATUS_NOINFOFILTER: 'No hay estados de usuarios actuales de este filtro ..',
    ABOUT_LICENSE0: 'WhatsSpy publico es una prueba de concepto para demostrar como es rota la configuracion de privacidad en WhatsApp. Con esta herramienta usted puede seguir basicamente cualquier comportamiento solo con el conocimiento de su numero de telefono. Esta herramienta es para Pruebas, solo con fines de Concepto ! Por favor, lea la',
    ABOUT_LICENSE1: 'Licencia',
    ABOUT_LICENSE2: 'Que se Aplica a este PoC.',
    ABOUT_DONATION0: 'Usted Puede Apoyar este Trabajo con una Minima Donacion:',
    ABOUT_DONATION1: 'Bitcoin:',
    ABOUT_DONATION2: 'O Via',
    ABOUT_DONATION3: 'Paypal',
    ABOUT_INFO: 'Informacion General',
    ABOUT_VERSION: 'Ejecutando la Version:',
    ABOUT_UPDATE: 'Esta Disponible.',
    ABOUT_UPTODATE: 'Su Version Esta Actualizada.',
    ABOUT_UPDATE_NOW: 'Actualizar',
    ABOUT_UPDATE_LOG: 'Actualizacion del Registro y Como Actualizar',
    ABOUT_WIKI: 'Pagina Wiki:',
    ABOUT_WIKI_LINK: 'Gitlab Wiki',
    ABOUT_FAQ: 'FAQ:',
    ABOUT_FAQ_LINK: 'Preguntas Frecuentes',
    ABOUT_TROUBLE: 'Solucion de Problemas:',
    ABOUT_TROUBLE_LINK: 'Solucion de Problemas',
    ABOUT_OPTIONS: 'Opciones:',
    ABOUT_OPTIONS_LOGOUT: 'Salir de la Interfaz Web',
    ABOUT_ADVANCED: 'Opciones Avanzadas:',
    ABOUT_ADVANCED_STOP: 'Detener Rastreador',
    ABOUT_ADVANCED_START: 'Iniciar Rastreador',
    ABOUT_ADVANCED_UPDATE: 'Actualizacion Automatica',
    ABOUT_NEWS: 'Literatura / Noticias del Proyecto:',
    ABOUT_AGENTS: 'Agentes de Notificacion',
    ABOUT_AGENTS_NONE1: 'No hay Agentes de Notificacion Configurados en',
    ABOUT_AGENTS_NONE2: 'config.php',
    ABOUT_AGENTS_NONE3: 'Compruebe config.example.php en caso de que haga falta estas opciones.',
    ABOUT_AGENTS_PROPS: 'Propiedades de Notificacion:',
    ABOUT_AGENTS_USER: 'Acciones del Usuario',
    ABOUT_AGENTS_TRACKER: 'Acciones de Seguimiento',
    ABOUT_AGENTS_TO: 'a:',
    ABOUT_AGENTS_RESTART: 'Recuerde que debe reiniciar el rastreador despues de cualquier cambio en su config.php.',
    ABOUT_LANGUAGE: 'Idioma:',
    ABOUT_QA: 'Preguntas y Respuestas',
    CONTROLLER_TIMELINE_1D: '24 Horas (Mejor Rendimiento)',
    CONTROLLER_TIMELINE_7D: '7  Dias',
    CONTROLLER_TIMELINE_14D: '14 Dias',
    CONTROLLER_TIMELINE_31D: '31 Dias (Lento)',
    CONTROLLER_TIMELINE_90D: '90 Dias (Muy Lento)',
    CONTROLLER_CHAR_OPENED: 'Abierto',
    CONTROLLER_CHAR_TIMES: 'Veces',
    CONTROLLER_CHAR_MINUTES: 'Minutos',
    CONTROLLER_COPY: 'Copiar al portapapeles: Ctrl + C, Enter',
    CONTROLLER_WEEKDAY_Sunday: 'Domingo',
    CONTROLLER_WEEKDAY_Monday: 'Lunes',
    CONTROLLER_WEEKDAY_Tuesday: 'Martes',
    CONTROLLER_WEEKDAY_Wednesday: 'Miercoles',
    CONTROLLER_WEEKDAY_Thursday: 'Jueves',
    CONTROLLER_WEEKDAY_Friday: 'Viernes',
    CONTROLLER_WEEKDAY_Saturday: 'Sabado',
    CONTROLLER_NONAME: 'Sin Nombre',
    CONTROLLER_NOTOKEN: 'No Compartido ...',
    CONTROLLER_TRACKER_REASON_NONE: 'No Dado',
    CONTROLLER_TIME_DAY: 'd',
    CONTROLLER_TIME_HOURS: 'h',
    CONTROLLER_TIME_MINUTES: 'min',
    CONTROLLER_TIME_SECONDS: 'seg',
    CONTROLLER_SERVER_NO_RES: 'No se ha Podido Contactar con el Servidor.',
    CONTROLLER_GROUP_NEW: 'Introduzca el Nuevo Nombre Para este Grupo:',
    CONTROLLER_ACCOUNT_DEL: 'Seguro que Quieres Borrar esta Cuenta?',
    CONTROLLER_ACCOUNT_REMOVED: ' Removido!',
    CONTROLLER_ACCOUNT_UPDATED: 'Contacto Actualizado',
    CONTROLLER_ACCOUNT_ADDED: 'Contacto Agregado a WhatsSpy. El Seguimiento comenzara en 5-10 Minutos.',
    CONTROLLER_ACCOUNT_INACTIVE: ' Conjunto Inactivo!',
    CONTROLLER_GROUP_SAVE: 'Guardado Nuevo Nombre de Grupo!',
    CONTROLLER_GROUP_ADD: 'Nuevo Grupo Agregado.',
    CONTROLLER_GROUP_DEL: 'Grupo Removido.',
    CONTROLLER_CONFIG_UPDATE: 'Configuracion Actualizada',
    CONTROLLER_TIME_DAY_FULL: 'Dia',
    CONTROLLER_TIME_WEEK_FULL: 'Semana',
    CONTROLLER_TIME_MONTH_FULL: 'Mes',
    CONTROLLER_TIME_CUSTOM_FULL: 'Personalizado',
    CONTROLLER_TIMELINE_HISTORY: 'Ver Historial:',
    CONTROLLER_TIMELINE_DAYS: 'Dia(s)',
    CONTROLLER_TIMELINE_ONLINE: 'Online',
    CONTROLLER_TIMELINE_DURATION: 'Duracion:',
    CONTROLLER_COMPARISON_ALREADY_IN: ' Esta Listo en la Comparacion!',
    CONTROLLER_NOTIFICATION_ONLINE: ' Esta Ahora Online.',
    CONTROLLER_NOTIFICATION_STATUSMSG: ' Tiene un Nuevo Mensaje de Estado: ',
    CONTROLLER_NOTIFICATION_PROFPIC: ' Ha Subido una Nueva Foto de Perfil.',
    CONTROLLER_NOTIFICATION_PIRV_EVERY: 'Todo',
    CONTROLLER_NOTIFICATION_PRIV_CONTACTS: 'Contactos o Nadie',
    CONTROLLER_NOTIFICATION_PRIV_LASTSEEN: ' Ha Cambiado la Configuracion de Privacidad de Ultima Vista ',
    CONTROLLER_NOTIFICATION_PRIV_PROFPIC: ' Ha Cambiado Su Privacidad En Foto de Perfil ',
    CONTROLLER_NOTIFICATION_PRIV_STATUSMSG: ' Ha Cambiado la Configuracion en su Mensaje de Estado ',
    CONTROLLER_NOTIFICATION_TRACKER_START: 'Rastreador Encendido Para Seguimiento.',
    CONTROLLER_NOTIFICATION_TRACKER_STOP: 'Rastreador ha Detenido el Seguimiento Por Motivo: ',
    CONTROLLER_STAT_TIMES: 'Veces',
    CONTROLLER_CMD0: 'CMD: ',
    CONTROLLER_CMD1: ' resulted in code: ',
    CONTROLLER_CMD2: ' with output: '
    });
    moment.locale('es', {
        months : [
            "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio",
            "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
        ],
        monthsShort : [
            "Ene", "Feb", "Mar", "Abr", "May", "Jun",
            "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"
        ],
        weekdays : [
            "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
        ],
        weekdaysShort : [
            "Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"
        ],
        longDateFormat : {
            LT: "h:mm A",
            LTS: "h:mm:ss A",
            L: "MM/DD/YYYY",
            l: "M/D/YYYY",
            LL: "MMMM Do YYYY",
            ll: "MMM D YYYY",
            LLL: "MMMM Do YYYY LT",
            lll: "MMM D YYYY LT",
            LLLL: "dddd, MMMM Do YYYY LT",
            llll: "ddd, MMM D YYYY LT"
        },
        relativeTime : {
            future: "in %s",
            past:   "%s atras",
            s:  "segundos",
            m:  "un minuto",
            mm: "%d minutos",
            h:  "una hora",
            hh: "%d horas",
            d:  "un dia",
            dd: "%d dias",
            M:  "un mes",
            MM: "%d meses",
            y:  "un año",
            yy: "%d añoss"
        }
    });

    $translateProvider.useSanitizeValueStrategy('escape');
    availableLanguages = [
        {
            id:'en', 
            name: 'English'
        }, 
        {
            id:'es', 
            name: 'Spanish (creator: Javier Andres Tolosa Rivera)'
        }];
    // Check if cookie exist, otherwise choose english.
    var cookieLang = getCookie('WSlanguage');
    if(cookieLang != undefined) {
        $translateProvider.preferredLanguage(cookieLang);
        moment.locale(cookieLang);
    } else {
        var language = 'en';
        $translateProvider.preferredLanguage(language);
        moment.locale(language);
    }
    console.log(cookieLang);

}]);